name: vendor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: 2.27.2
#  firebase_auth: 4.18.0
#  google_maps_flutter: ^2.6.0
  geocoding: ^3.0.0
  geolocator: any




  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true

